### ISSUE TITLE
Form Level reward fix

### ISSUE THREAD

**Issue by goldspacedragon** [Zurphing/DoublePlus#1]
I found the necessary values to make a vanilla run with DoublePlus function correctly. 
They fall under the "Ability:" row in the Fmlvlist.yml, and they are as follows:
High Jump lvl 1: 94   Aerial Dodge lvl 1: 102
High Jump lvl 2: 95   Aerial Dodge lvl 2: 103
High Jump lvl 3: 96   Aerial Dodge lvl 3: 104
High Jump lvl 4: 97   Aerial Dodge lvl 4: 105
Quick Run lvl 1: 98   Glide lvl 1: 106
Quick Run lvl 2: 99   Glide lvl 2: 107
Quick Run lvl 3: 100   Glide lvl 3: 108
Quick Run lvl 4: 101   Glide lvl 4: 109

I tested the values 97, 98, 99, and 100, and noticed the pattern. I just filled in the blanks from there.

**Comment by goldspacedragon** [comment]
I forgot Dodge roll, will have to revise in a few minutes once I find it

**Comment by Zurphing** [comment]
![image](https://user-images.githubusercontent.com/72351816/193719281-d28f6567-aa00-424e-9474-89f526366596.png)
This is a vanilla, unmodified fmlv file. In the vanilla game, the "Ability" slot is deliberately left empty, as the game doesn't assign growth abilities to the "Ability" row. if I assigned abilities there what would likely happen is you get High Jump LVL 1, and when you unlocked High Jump LVL 2, you'd see both High Jump LVL 1 and 2 in your growth ability list. 

Can you reconfirm your setup?
Is this a fresh save file started since the update, or are you continuing the old one that had this issue?
What combination of mods are you using?
Are you using the GoA ROM lua script?

**Comment by goldspacedragon** [comment]
I'm using everything correctly, the fmlvl file's rewards for base Sora are all zero's tho
except for 4 and 6 where you get the non-movement utilities
the save does not matter, the fmlvl file does as long as I hit build in between changes

**Comment by goldspacedragon** [comment]
It's very...strange. but the values I found above are correct, I just need to find Dodge Roll now

**Comment by Zurphing** [comment]
Then I'm not sure this is a Double Plus issue. It's working fine on my end.
![image](https://user-images.githubusercontent.com/72351816/193721149-cb020069-eae7-4808-9c22-be4899deab45.png)

My best guess is something in your setup is causing things to not work as expected, how do you have your mod list setup?

**Comment by goldspacedragon** [comment]
sure, one sec.

**Comment by goldspacedragon** [comment]
![image](https://user-images.githubusercontent.com/55035362/193721246-5c5cc2e8-27dd-441f-965b-541925ca163b.png)
das it

**Comment by goldspacedragon** [comment]
do I need to show you my cheats folder as well just in case?
Anything else that could clash?

**Comment by goldspacedragon** [comment]
Also, emulator, so that might have something to do with it

**Comment by Zurphing** [comment]
And to double check, is your GoA ROM Lua loading? I.e you can return to Garden when you reach a save point.

**Comment by goldspacedragon** [comment]
I've been using that all the time, so yeah

**Comment by Zurphing** [comment]
Might be the issue then. As far as I've experienced, trying to use that on my non rando save files has led to my growth abilities being deleted. Try not using it and see if that changes anything.

**Comment by goldspacedragon** [comment]
I had Goa Ram Non rando in scripts, would that be a problem?

**Comment by Zurphing** [comment]
Trying to mix GoA RAM & GoA ROM is never a good idea, so yes.

**Comment by goldspacedragon** [comment]
gonna go make my fmlvlist the way it was before and see if it's fine now

**Comment by goldspacedragon** [comment]
Nooope, nothing changed

**Comment by goldspacedragon** [comment]
So what would be next? Updating GoA ROM for the umpteenth time?

**Comment by Zurphing** [comment]
Just to double check, can you remove **all** of the scripts in your scripts folder and try again

**Comment by goldspacedragon** [comment]
It changed...?
It said it gave master aerial dodge 2
that's it

**Comment by goldspacedragon** [comment]
Gonna see what happened in a second as long as I don't die

**Comment by goldspacedragon** [comment]
Yup. No movement for me, ability for master,

**Comment by goldspacedragon** [comment]
And it didn't change at all from before, where I would get the ability change even though it wasn't reflected in the text
so weird

**Comment by goldspacedragon** [comment]
What's different between our setups, by the way? Other than the emu-pc difference

**Comment by Zurphing** [comment]
Nothing about the two setups are different.

I'm fairly certain the issue will continue to affect your save file. When Sora doesn't get the growth ability for level 1, he'll continue to not gain higher tiers of the growth ability even if the Forms level of the growth ability goes up.

I don't know if GoA ROM is intended to be used non-rando, perhaps it's better to use the GoA RAM Non Rando lua. If you restart the save file it should go back to normal, but beyond that, this is not a Double Plus issue.

**Comment by goldspacedragon** [comment]
Okay then. 
I'll check it, use the same route as before. 
Zoom to master, check it, and pray

**Comment by goldspacedragon** [comment]
Wait, can I use the goa rom mod in the manager and the ram non rando in the scripts? Is that okay?

**Comment by Zurphing** [comment]
I don't know for certain, just that generally speaking mixing GoA ROM & RAM has usually led to issues for other people in the past. GoA RAM Non rando should do everything ROM would do, just without stuff like door icons.

**Comment by goldspacedragon** [comment]
okey

**Comment by goldspacedragon** [comment]
Another issue
whenever I use non rando GoA, I don't start in the station of awakening
It's straight to stt

**Comment by goldspacedragon** [comment]
It's why I've stayed away from that setup, because it doesn't work properly it seems

**Comment by goldspacedragon** [comment]
I don't know what I could be missing to make this work properly, it make no sense

**Comment by goldspacedragon** [comment]
Do you think it might be easier if you made a non-rando Goa Rom compatible version instead of all of the headache that this entails?

**Comment by Zurphing** [comment]
Nothing about the mod itself is incompatible. I can't change anything to make it more compatible because the issues you're experiencing with growth abilities are tied to the lua script found in GoA ROM. Closing the issue.
